syntax = "proto3";


option java_package = "com.jun.grpc.order";

option java_multiple_files = true;


service OrderService {
  rpc CreateOrder (CreateOrderRequest) returns (CreateOrderResponse);
  rpc UpdateOrderStatus (UpdateOrderStatusRequest) returns (UpdateOrderStatusResponse);
  rpc GetOrders (GetOrdersRequest) returns (GetOrdersResponse);
}

service MenuService {
  rpc AddMenu (MenuRequest) returns (MenuResponse);
  rpc GetMenus (Empty) returns (MenuListResponse);
}

message GetOrdersRequest {
  string customerId = 1;
}

message GetOrdersResponse {
  repeated OrderInfo orders = 1;
}

message OrderInfo {
  string orderId = 1;
  string customerId = 2;
  string restaurantId = 3;
  string menuName = 4;
  int32 price = 5;
  string status = 6;
}

message CreateOrderRequest {
  string customerId = 1;
  string restaurantId = 2;
  string menuName = 3;
  int32 price = 4;
}

message CreateOrderResponse {
  string orderId = 1;
  string status = 2; // 주문 상태
  string message = 3; // 결과 메시지
}

message UpdateOrderStatusRequest {
  string orderId = 1;
  string status = 2;
}

message UpdateOrderStatusResponse {
  string orderId = 1;
  string status = 2;
}

message MenuRequest {
  string name = 1;
  int32 price = 2;
  string description = 3;
}

message MenuResponse {
  int64 id = 1;
  string name = 2;
  int32 price = 3;
}

message Empty {}

message MenuListResponse {
  repeated MenuResponse menus = 1;
}
