plugins {
    id 'java-library'
    id 'com.google.protobuf' version '0.9.4'
}

group = 'com.jun'
version = '0.0.1-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'io.grpc:grpc-protobuf:1.76.0'
    implementation 'io.grpc:grpc-stub:1.76.0'

    // Java에서 Protobuf 메시지를 사용하기 위한 라이브러리
    implementation 'com.google.protobuf:protobuf-java:3.25.8'

    // javax.annotation.Generated 어노테이션을 위한 의존성
    implementation 'javax.annotation:javax.annotation-api:1.3.2'
}

protobuf {
    protoc {
        artifact = 'com.google.protobuf:protoc:3.25.8'
    }
    plugins {
        // gRPC 자바 플러그인 설정
        grpc {
            artifact = 'io.grpc:protoc-gen-grpc-java:1.76.0'
        }
    }

    // gRPC 플러그인을 사용하도록 설정
    generateProtoTasks {
        all()*.plugins {
            grpc {}
        }
    }
}

sourceSets {
    main {
        java {
            srcDirs(
                    "$buildDir/generated/source/proto/main/java",
                    "$buildDir/generated/source/proto/main/grpc"
            )
        }
    }

}
